name: Release
run-name: Release
on: workflow_dispatch
jobs:
  create-and-release:
    name: Create and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          preset: "conventionalcommits"
          version-file: "Assets/Plugins/ExecutionController/package.json"
          input-file: "./CHANGELOG.md"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: FVCodePublisher
          git-user-email: codepublish@futureverse.com

      - name: Find package files
        if: steps.changelog.outputs.skipped != 'true'
        run: |
          echo "Assets/Plugins/ExecutionController.meta" >> metalist
          find "Assets/Plugins/ExecutionController/" -name \*.meta >> metaList

      - name: Create Package
        if: steps.changelog.outputs.skipped != 'true'
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: ExecutionController.unitypackage
          include-files: metaList

      - name: Create GitHub release
        if: steps.changelog.outputs.skipped != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          name: v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: ExecutionController.unitypackage
